//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.PrxOlaMundo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrxOlaMundo.IOlaMundoService")]
    public interface IOlaMundoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOlaMundoService/OlaMundo", ReplyAction="http://tempuri.org/IOlaMundoService/OlaMundoResponse")]
        string OlaMundo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOlaMundoService/OlaMundo", ReplyAction="http://tempuri.org/IOlaMundoService/OlaMundoResponse")]
        System.Threading.Tasks.Task<string> OlaMundoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOlaMundoServiceChannel : Client.PrxOlaMundo.IOlaMundoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OlaMundoServiceClient : System.ServiceModel.ClientBase<Client.PrxOlaMundo.IOlaMundoService>, Client.PrxOlaMundo.IOlaMundoService {
        
        public OlaMundoServiceClient() {
        }
        
        public OlaMundoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OlaMundoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OlaMundoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OlaMundoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string OlaMundo() {
            return base.Channel.OlaMundo();
        }
        
        public System.Threading.Tasks.Task<string> OlaMundoAsync() {
            return base.Channel.OlaMundoAsync();
        }
    }
}
